name: Build Armbian Image T95Z

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Armbian Builder Action
        uses: armbian/build@main
        with:
          armbian_token: ${{ secrets.GITHUB_TOKEN }}
          armbian_board: "aml-t95z-plus"
          armbian_branch: "current"       
          armbian_release: "bookworm"        
          armbian_target: "image"
          armbian_ui: "minimal"
          armbian_runner_clean: "yes"

